blogapp/apps/profiles/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    ProfileView,
    MyProfileView,
)

urlpatterns = [
    path('myprofile/', MyProfileView.as_view(), name='my_profile'),
    path('<slug:slug>/', ProfileView.as_view(), name='profiles'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blogapp/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from user_authentication.views import RegisterView, LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.welcome.urls')),
    path('welcome/', include('apps.welcome.urls')),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('logout/', LogoutView),
    path('blog/', include('apps.blog.urls')),
    path('profiles/', include('apps.profiles.urls')),
    path('ckeditor/', include('django_ckeditor_5.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

blogapp/apps/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
import uuid

def validate_file_size(value):
    image_size = value.size
    if image_size > 1024 * 256:
        raise ValidationError('File size cannot exceed 0.5 MB.')

def generate_unique_filename(_, filename):
    ext = filename.split('.')[-1]
    unique_filename = f'{uuid.uuid4()}.{ext}'
    return f'profile_images/{unique_filename}'
    

# Create your models here.
class Profile(models.Model):
    user  = models.ForeignKey(User, on_delete=models.CASCADE)
    bio   = models.CharField(max_length=240, blank=True)
    image = models.ImageField(
        upload_to=generate_unique_filename,
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
            validate_file_size
        ],
        blank=True,
        null=True
    )

    def __str__(self):
        return f'{self.user}'
    
    def img_src(self):
        return f'/media/{self.image}' if self.image else "/static/favicons/favicon.ico"

blogapp/apps/profiles/forms.py
from django import forms

from .models import Profile

class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'image',
        )

blogapp/apps/profiles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth.models import User
from django.http import JsonResponse

from .models import Profile, generate_unique_filename
from .forms import ProfileImageForm
from utilities.authenticators import when_logged_inc

# Create your views here.
class ProfileView(View):

    def get(self, request, slug, *args, **kwargs):        
        user = get_object_or_404(User, username=slug)
        profile = get_object_or_404(Profile, user=user)

        context = {
            'profile' : profile
        }

        return render(request, 'profiles/index.html', context)

class MyProfileView(View):

    @when_logged_inc
    def get(self, request, *args, **kwargs):

        user = request.user
        profile = get_object_or_404(Profile, user=user)
        print(profile.image)
        
        context = {
            'profile' : profile,
            'profileImageForm' : ProfileImageForm(),
        }
        return render(request, 'profiles/detail.html', context)
    
    @when_logged_inc
    def post(self, request, *args, **kwargs):
        profile = get_object_or_404(Profile, user=request.user)
        try:
            print(request.POST, request.FILES)
            if 'bio_data' in request.POST:
                profile.bio = request.POST.get('bio_data')
                profile.save()
                return JsonResponse({'response': profile.bio})
            if 'image' in request.FILES:
                form = ProfileImageForm(request.POST, request.FILES, instance=profile)
                if form.is_valid():
                    form.save()
                else:
                    print('not valid', form.errors)
                return redirect('.')
                
        except Exception as e:
            print('xd', e)

blogapp/apps/profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}Mój Profil{% endblock %}

{% block body %}
<section style="background-color: #eee;">
    <div class="container py-5">
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">

            <a href="#" data-bs-toggle="modal" data-bs-target="#profile_image_modal">
              <img src="{{profile.img_src}}" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
            </a>
              <div class="modal fade" id="profile_image_modal" tabindex="-1" aria-labelledby="profile_imageLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="profile_imageLabel">Edytuj swoje zdjęcie profilowe</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <form method = "post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{profileImageForm.image}}
                      <button type="submit">Zmień zdjęcie</button>
                    </form>

                  </div>
                </div>
              </div>

              <h5 class="my-3">{{profile.user.username}}</h5>
              <p class="text-muted mb-1">
                <p id="bio-ajax-response">{{profile.bio}}</p>
                <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#bio_modal">
                    <i class="bi bi-pen"></i> bio
                </a>
                  <div class="modal fade" id="bio_modal" tabindex="-1" aria-labelledby="bio_modalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h1 class="modal-title fs-5" id="bio_modalLabel">Edytuj swoje bio</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>

                          <form id="bio-ajax-form"> {% csrf_token %}
                            <div class="modal-body">
                              <textarea cols="30" id="id_bio" name="bio_data">{{profile.bio}}</textarea>
                            </div>
                            <div class="modal-footer">
                              
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Anuluj</button>
                              <button type="submit" class="btn btn-primary">Edytuj</button>
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                </p>
              <div class="d-flex justify-content-center mb-2">
                <button type="button" class="btn btn-primary">Follow</button>
                <button type="button" class="btn btn-outline-primary ms-1">Message</button>
              </div>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fas fa-globe fa-lg text-warning"></i>
                  <p class="mb-0">https://mdbootstrap.com</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                  <p class="mb-0">@mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                  <p class="mb-0">mdbootstrap</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Login</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{profile.user.username}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{profile.user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">(097) 234-5678</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Mobile</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">(098) 765-4321</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">Bay Area, San Francisco, CA</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                  </p>
                  <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                  <div class="progress rounded mb-2" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                  </p>
                  <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                  <div class="progress rounded mb-2" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> 

<script>
  $(document).ready(function () {
      var csrfToken = $("[name=csrfmiddlewaretoken]").val();
      $('#bio-ajax-form').on('submit', function (event) {
        event.preventDefault();
        $.ajax({
            url: '/profiles/myprofile/',
            type: 'POST',
            data: {
                'bio_data': $('#id_bio').val()
            },
            headers: {
              "X-CSRFToken": csrfToken
            },
            dataType: 'json',
            success: function (data) {
              $('#bio-ajax-response').text(data.response);
              $('#bio_modal').modal('hide');
            }
        });
      });

      $('#profile_image-ajax-form').on('submit', function (event) {
        event.preventDefault();
        alert($('#formFileSm').val());
        $.ajax({
            url: '/profiles/myprofile/',
            type: 'POST',
            data: {
                'profile_image': $('#formFileSm').val()
            },
            headers: {
              "X-CSRFToken": csrfToken
            },
            dataType: 'json',
            success: function (data) {
              $('#profile_image_modal').modal('hide');
            }
        });
      });
  });
</script>
{% endblock %}

blogapp/apps/profiles/templates/profiles/index.html
{% extends 'base.html' %}

{% block title %}{{profile}} - profil{% endblock %}

{% block body %}
<section style="background-color: #eee;">
    <div class="container py-5">
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">

              <img src="{{profile.img_src}}" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">{{profile.user.username}}</h5>
              <p class="text-muted mb-1">
                <p>{{profile.bio}}</p>
              </p>
              <div class="d-flex justify-content-center mb-2">
                <button type="button" class="btn btn-primary">Follow</button>
                <button type="button" class="btn btn-outline-primary ms-1">Message</button>
              </div>
            </div>
          </div>
          </div>
        </div>
      </div>
</section> 
{% endblock %}