blogapp/apps/blog/urls.py
from django.urls import path

from .views import (
    BlogView,
    PostCreateView,
    PostView,
    PostDeleteView,
    PostEditView
)

urlpatterns = [
    path('', BlogView.as_view(), name='posts'),
    path('create/', PostCreateView.as_view(), name='posts-create'),
    path('delete/<slug:slug>/', PostDeleteView.as_view(), name='posts-delete'),
    path('edit/<slug:slug>/', PostEditView.as_view(), name='posts-edit'),
    path('<slug:slug>/', PostView.as_view(), name='posts-detail'),
]

blogapp/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from user_authentication.views import RegisterView, LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.welcome.urls')),
    path('welcome/', include('apps.welcome.urls')),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('logout/', LogoutView),
    path('blog/', include('apps.blog.urls')),
    path('profiles/', include('apps.profiles.urls')),
    path('ckeditor/', include('django_ckeditor_5.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

blogapp/apps/blog/models.py
from django.db import models
from django.conf import settings
from datetime import datetime, timezone
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from unidecode import unidecode
from django_ckeditor_5.fields import CKEditor5Field
from random import randint

from apps.profiles.models import Profile
from apps.comments.models import Comment
    
class Post(models.Model):
    class Meta:
        ordering = ["-publish_date"]

    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    body = CKEditor5Field()
    meta_description = models.CharField(max_length=150, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    publish_date = models.DateTimeField(blank=True, null=True)
    published = models.BooleanField(default=False)

    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    root_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, blank=True, null=True)

    def get_post_preview(self):
        return self.body[:200] + '...'

    def number_of_views(self):
        return len(self.body)

    def time_passed_from_date(self):
        current_date = datetime.now(timezone.utc)
        time_difference = current_date - self.publish_date

        days = time_difference.days
        if days > 365:
            return f'{int(days / 365)} lat temu'

        if days > 0:
            return f'{days} dni temu'
        
        seconds = time_difference.seconds
        if seconds > 3600:
            return f'{int(seconds / 3600)} godzin temu'

        if seconds > 60:
           return f'{int(seconds / 60)} minut temu' 

        return f'{seconds} sekund temu'

    def get_published_date(self):
        import locale
        locale.setlocale(locale.LC_TIME, 'pl_PL.utf8')
        input_format = '%d %B %Y'
        return self.publish_date.date().strftime(input_format)

    def get_published_hour(self):
        minutes = self.publish_date.minute
        minutes = f'{minutes}' if minutes > 9 else f'0{minutes}'
        return f'{self.publish_date.hour}:{minutes}'
    
    def get_slug(self):
        return f'{slugify(unidecode(self.title))}-{randint(1,10000)}'
    
    def get_absolute_url(self):
        return reverse('posts-detail', kwargs={'slug':self.slug})
    def get_absolute_delete_url(self):
        return reverse('posts-delete', kwargs={'slug':self.slug})
    def get_absolute_edit_url(self):
        return reverse('posts-edit', kwargs={'slug':self.slug})

blogapp/apps/blog/forms.py
from django import forms
from datetime import datetime
from django_ckeditor_5.widgets import CKEditor5Widget


from .models import Post
from apps.comments.models import Comment

class CustomCKEditorWidget(CKEditor5Widget):
    def render(self, name, value, attrs=None, renderer=None):
        # Call the parent class's render method
        rendered = super().render(name, value, attrs, renderer)
        
        # # Customize the attributes
        # new_attrs = {'class': 'my-custom-class', 'style': 'display: block;'}
        # rendered = rendered.replace('class="django-ckeditor-widget"', f'class="django-ckeditor-widget {new_attrs["class"]}"')
        # rendered = rendered.replace('style="display: inline-block;"', f'style="{new_attrs["style"]}"')

        return rendered

class PostForm(forms.ModelForm):
    title    = forms.CharField(label='Tytuł', widget=forms.TextInput(attrs={'class': 'form-control'}))
    subtitle = forms.CharField(label='Podtytuł', widget=forms.TextInput(attrs={'class': 'form-control'}))
    body     = forms.CharField(label='', widget=CustomCKEditorWidget())
    #body     = RichTextFormField(label='', )
    #body     = forms.CharField(label='Treść', widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'height: 100%;'}))

    class Meta:
        model = Post
        fields = (
            'title',
            'subtitle',
            # 'body',
        )

    def __init__(self, *args, **kwargs):
        kwargs["label_suffix"] = ""
        super().__init__(*args, **kwargs)

    def save(self, author, create=False, commit=True):
        print('saving')
        print(self.data)
        post = super(PostForm, self).save(commit=False)
        post.author = author
        post.body = self.data['body']
        if create:
            post.publish_date = datetime.now()
            print('lol1')
            post.root_comment = Comment.objects.create()
            print('lol2')
        else:
            post.date_modified = datetime.now()

        if create or post.slug == None:
            post.slug = post.get_slug()

        if commit:
            post.save()
            
        return post

blogapp/apps/comments/forms.py
from django import forms
from datetime import datetime

from .models import Comment

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='Dodaj komentarz', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}))
    parent  = forms.IntegerField(widget=forms.TextInput(attrs={'type': 'hidden', 'value': -1}))
    #<input type="hidden" name="parent" value="-1">
    class Meta:
        model = Comment
        fields = (
            'content',
        )

    def save(self, author, commit=True):
        comment = super(CommentForm, self).save(commit=False)
        comment.author = author
        
        comment.publish_date = datetime.now()
        if commit:
            comment.save()

        return comment

blogapp/apps/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import ListView
from django.http import Http404

from .models import Post
from .forms import PostForm

from apps.profiles.models import Profile
from apps.comments.models import Comment
from apps.comments.forms import CommentForm

from utilities.authenticators import when_logged_inc

# Create your views here.
class BlogView(ListView):
    paginate_by = 2
    model = Post
    
    def get(self, request, *args, **kwargs):
        try:
            page = abs(int(request.GET['page']))
            size = abs(int(request.GET['size']))
            amount = int(Post.objects.count() / size)
            amount, divrest = divmod(Post.objects.count(), size)
            amount = amount + 1 if divrest else amount
            if page == 0 or page > amount:
                raise Exception('Only one page')
            context = {
                'objects' : Post.objects.all()[page * size - size : page * size],
                'page' : page,
                'size' : size,
                'amount' : amount,
                'has_previous': page != 1,
                'has_next' : page != amount,
                'previous_page_number' : page - 1,
                'next_page_number' : page + 1,
            }
        except:
            page = 1
            amount, divrest = divmod(Post.objects.count(), 10)
            amount = amount + 1 if divrest else amount
            context = {
                'objects' : Post.objects.all()[:10],
                'page' : page,
                'amount' : int(Post.objects.count() / 10) + 1,
                'has_previous': False,
                'has_next' : page != amount,
                'next_page_number' : page + 1
            }

        return render(request, 'blog/index.html', context)

class PostCreateView(View):

    @when_logged_inc
    def get(self, request, form=None, *args, **kwargs):
        form = form or PostForm()
        context = {
            'post_form' : form
        }
        return render(request, 'blog/create.html', context)
    
    @when_logged_inc
    def post(self, request, form=None, *args, **kwargs):
        create_flag = form == None
        form = form or PostForm(request.POST)
        if form.is_valid():
            print('VALID:', request.POST)
            profile = get_object_or_404(Profile, user=request.user)
            post = form.save(profile, create=create_flag)
            return redirect(f'/blog/{post.slug}/')
        context = {
            'post_form' : form
        }
        return render(request, 'blog/create.html', context)
    

class PostView(View):

    def get(self, request, slug, *args, **kwargs):
        obj = get_object_or_404(Post, slug=slug)
        recent_posts = [(p.title, p.get_published_date(), p.slug) for p in Post.objects.filter(author=obj.author)[:3]]
        comment_form = CommentForm()
        #comment_form.parent.widget.attrs['value'] =obj.root_comment.id
        context = {
            'obj' : obj,
            'recent_posts' : recent_posts,
            'comment_form' : comment_form,
        }
        return render(request, 'blog/detail.html', context)
    
    def post(self, request, slug, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            profile = get_object_or_404(Profile, user=request.user)
            post = get_object_or_404(Post, slug=slug)
            comment = form.save(profile)
            parentid = int(form.cleaned_data['parent'])
            parentid = parentid if parentid != -1 else post.root_comment.id
            parent = get_object_or_404(Comment, id=parentid)
            parent.children_comments.add(comment)
            post.root_comment = post.root_comment or comment
            #post.comments.add(comment)
            #post.save()
        return redirect('./#CommentSection')

class PostDeleteView(View):

    @when_logged_inc
    def post(self, request, slug, *args, **kwargs):
        obj = get_object_or_404(Post, slug=slug)
        if obj.author.user == request.user:
            if obj.root_comment:
                obj.root_comment.delete_comment()
            obj.delete()
        return redirect('/blog/')
    
    @when_logged_inc
    def get(self, request, slug, *args, **kwargs):
        raise Http404('Ta strona nie istnieje')

class PostEditView(PostCreateView):
    
    @when_logged_inc
    def get(self, request, slug, *args, **kwargs):
        obj = get_object_or_404(Post, slug=slug)
        form = PostForm(instance=obj)
        return super().get(request, form=form)
    
    @when_logged_inc
    def post(self, request, slug, *args, **kwargs):
        obj = get_object_or_404(Post, slug=slug)
        print(request.POST)
        form = PostForm(request.POST or None, instance=obj)
        super().post(request, form=form)
        return redirect(f'/blog/{slug}/')

blogapp/apps/blog/templates/blog/comments_tree copy.html
{% for comment in comments %}
    <div class="comment" style="margin-left: 20px;">
        <p>{{ comment.content }}</p>
        <p>Posted on {{ comment.publish_date}}</p>
        
        {% if comment.replies.count > 0 %}
            <div class="replies">
                {% include 'blog/comments_tree.html' with comments=comment.replies.all %}
            </div>
        {% endif %}
    </div>
{% endfor %}

blogapp/apps/blog/templates/blog/comments_tree.html
{% for comment in comments %}
<div class="d-flex flex-start">
    <a href="/profiles/{{comment.author}}"><img class="rounded-circle shadow-1-strong me-3" src="{{comment.author.img_src}}" alt="{{comment.author}}_profile_image" width="65" height="65"></a>
    <div class="flex-grow-1 flex-shrink-1">
        <div>
            <div class="d-flex justify-content-between align-items-center">
              <p class="mb-1">
                <a href="/profiles/{{comment.author}}" style="text-decoration: none;" >{{comment.author}}</a>
                <span class="small">- {{ comment.time_passed_from_date}}</span>
                <a class="showContainer btn" data-div-id="divContainer{{ comment.id }}"><i class="bi bi-reply"></i> </i><span class="small"></span></a>
                <i class="bi bi-plus-circle"></i>
              </p>
            </div>
                <div style="overflow-wrap: anywhere;">{{ comment.content }}</div>
                <div id="divContainer{{comment.id}}" style="display: none;">
                    <form method="POST"> {% csrf_token %}
                        {{comment_form.content.label}}
                        {{comment_form.content}}
                        <input type="hidden" name="parent" value="{{comment.id}}" id="id_parent">
                        <button class="btn btn-primary" type="submit">Wyślij</button>
                    </form>
                </div>
        </div>
        <hr>
        {% if comment.children_comments.count > 0 %}
                {% include 'blog/comments_tree.html' with comments=comment.children_comments.all %}
        {% endif %}
    </div>
</div>
{% endfor %}

blogapp/apps/blog/templates/blog/create.html
{% extends 'base.html' %}

{% block title %}Stwórz Post{% endblock %}

{% block body %}
    <div class="container mt-3">
        <h1>Napisz posta</h1>
        <form method="POST"> {% csrf_token %}
            
            {% for field in post_form %}
                <div class="form-floating mb-3 mt-3">
                    {{ field }}
                    {{ field.label_tag }}
                </div>
            {% endfor %}
            {{post_form.media}}
            <button class="btn btn-primary" type="submit">Wyślij</button>
        </form>
    </div>


{% endblock %}

blogapp/apps/blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{obj.title}}{% endblock %}

{% block style %}
<style>
  .gradient-custom { /* fallback for old browsers */ background: #4facfe; /* Chrome 10-25,
  Safari 5.1-6 */ background: -webkit-linear-gradient(to bottom right, rgba(79, 172, 254,
  1), rgba(0, 242, 254, 1)); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+,
  Safari 7+ */ background: linear-gradient(to bottom right, rgba(79, 172, 254, 1), rgba(0,
  242, 254, 1)) }

  .list-unstyled li {
    border-bottom: 1px solid #ccc; /* Add a border at the bottom of each list item */
    padding-bottom: 10px; /* Optional: Add some spacing between list items */
    margin-bottom: 10px; /* Optional: Add some spacing between list items */
    list-style: none; /* Remove default list styling */
  }
  .modal-backdrop {
    z-index: -1;
  }
  .hidden-textarea {
    display: none;
  }
</style>
{% endblock %}  

{% block body %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <div id="intro" class="p-5 text-center bg-light">
      <h1 class="mb-0 h4">{{obj.title}}</h1>
    </div>

  <main class="mt-4 mb-5">
    <div class="container">
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="border-bottom mb-4">
            <img src="https://mdbootstrap.com/img/Photos/Slides/img%20(144).jpg"
              class="img-fluid shadow-2-strong rounded-5 mb-4" alt="" >

            <div class="row align-items-center mb-4">
              <div class="col-lg-6 text-center text-lg-start mb-3 m-lg-0">
                <img src="{{obj.author.img_src}}" alt="{{obj.author}} profile image" class="rounded-5 shadow-1-strong me-2" height="35" alt="" loading="lazy">
                  <span><i class="fa fa-user"></i> <a href="/profiles/{{obj.author}}" style="text-decoration: none;">{{obj.author}}</a></span>
                  <span><i class="fa fa-calendar"></i> {{obj.get_published_date}}</span>
              </div>

              <div class="col-lg-6 text-center text-lg-end">
                <button type="button" class="btn btn-primary px-3 me-1" style="background-color: #3b5998;">
                  <i class="bi bi-facebook"></i>
                </button>
                <button type="button" class="btn btn-primary px-3 me-1" style="background-color: #55acee;">
                  <i class="bi bi-twitter-x"></i>
                </button>
                <button type="button" class="btn btn-primary px-3 me-1" style="background-color: #0082ca;">
                  <i class="bi bi-linkedin"></i>
                </button>
                <a href="#CommentSection" class="btn btn-primary px-3 me-1">
                  <i class="bi bi-chat"></i>
                </a>
              </div>
              <p>{{obj.subtitle}}</p>
            </div>
          </div>
          <div>
            {{obj.body | safe}}
          </div>

          <div class="text-center border-top border-bottom py-4 mb-4"></div>

          <div class="border-bottom mb-4 pb-4">
            <div class="row">
              <div class="col-3">
                <img src="{{obj.author.img_src}}" class="shadow-1-strong rounded-5 me-2" height="60" alt="{{obj.author}} profile image">
              </div>

              <div class="col-9">
                <p class="mb-2"><strong><a href="/profiles/{{obj.author}}" style="text-decoration: none;">{{obj.author}}</a></strong></p>
                <p>
                  {{obj.author.bio}}
                </p>
              </div>
            </div>
          </div>

          

        </div>

        <div class="col-md-4 mb-4">
          <div class="sticky-top" style="top: 80px;">            

            <div class="text-center border-bottom pb-4 mb-4">
              {% if obj.author.user == user %}
                <div class="card mb-3" style="width: 18rem;">
                    <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editModal">
                        <i class="bi bi-pen"></i>
                    Edytuj Posta
                    </a>
                    <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h2 class="modal-title fs-5" id="editModalLabel">Czy na pewno chcesz edytować tego posta?</h2>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              Edytuj {{obj.title}}
                            </div>
                            <div class="modal-footer">

                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Anuluj</button>
                              <a href="{{obj.get_absolute_edit_url}}" class="btn btn-primary">Tak, edytuj</a>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>

                <div class="card mb-3" style="width: 18rem;">
                    <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#deleteModal">
                    <i class="bi bi-trash3"></i>
                    Usuń Posta
                    </a>
                    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h2 class="modal-title fs-5" id="deleteModalLabel">Czy na pewno chcesz usunąć tego posta?</h2>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              Usuń {{obj.title}}
                            </div>
                            <div class="modal-footer">

                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Anuluj</button>
                              <form method="POST" action="{{obj.get_absolute_delete_url}}"> {% csrf_token %}
                                  <button type="submit" class="btn btn-primary">Tak, usuń</button>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>
            {% endif %}
            </div>

            <div class="border-bottom pb-4 mb-4">
              <a href=".." style="text-decoration: none;"><i class="bi bi-arrow-left"></i> Wróć do postów</a>
              <hr class="solid">

              <h5>Ostatnie posty  <a href="/profiles/{{obj.author}}" style="text-decoration: none;">{{obj.author}}</a></h5>
              <div class="box posts">
                <ul class="list-unstyled">
                    {% for recent_post in recent_posts %}
                        <li>
                            <i class="bi bi-file-post"></i>
                            <a href="/blog/{{recent_post.2}}" style="text-decoration: none;">{{recent_post.0}}</a>
                            <div>
                                <i class="bi bi-calendar-date"></i> {{recent_post.1}}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
              </div>
            </div>
            <div class="border-bottom pb-4 mb-4">
              <h5>Kategorie</h5>
              <div class="box categories">
                  <ul class="list-unstyled">
                      <li><a href="#">Kategoria</a></li>
                      <li><a href="#">Kategoria</a></li>
                      <li><a href="#">Kategoria</a></li>
                      <li><a href="#">Kategoria</a></li>
                  </ul>
              </div>
            </div>
            <div class="border-bottom pb-4 mb-4">
              <h5>Tagi</h5>
              <div class="box tags">
                <ul class="blog-tags list-unstyled list-inline">
                    <li><a href="#"><i class="fa fa-tag"></i>Tag</a></li>
                    <li><a href="#"><i class="fa fa-tag"></i>Tag</a></li>
                    <li><a href="#"><i class="fa fa-tag"></i>Tag</a></li>
                    <li><a href="#"><i class="fa fa-tag"></i>Tag</a></li>
                </ul>
            </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  </main>

    <div class="container my-5 py-5" id="CommentSection">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12 col-lg-10 col-xl-8">
          <div class="card">
            <div class="card-body p-4">
              <h4 class="text-center mb-4 pb-2">Komentarze</h4>
              <div class="row">
                <div class="col">

                  <div>
                    <form method="POST"> {% csrf_token %}
                      {{comment_form.as_p}}
                      <button class="btn btn-primary" type="submit">Wyślij</button>
                    </form>
                  </div>
                  <hr>
                  {% if obj.root_comment.children_comments.count %}
                    {% include './comments_tree.html' with comments=obj.root_comment.children_comments.all %}
                  {% endif %}

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <script>
    // Add a click event listener to all elements with the class "showContainer"
    var showContainerButtons = document.querySelectorAll(".showContainer");

    showContainerButtons.forEach(function(button) {
        button.addEventListener("click", function () {
            var divId = button.getAttribute("data-div-id");

            var container = document.getElementById(divId);

            if (container.style.display === "none") {
                container.style.display = "block";
            } else {
                container.style.display = "none";
            }
        });
    });
</script>

{% endblock %}

blogapp/apps/blog/templates/blog/edit.html
{% extends 'base.html' %}

{% block title %}Edytuj Post{% endblock %}

{% block body %}
    <div class="container mt-3">
        <h1>Edytuj posta</h1>

        {% for field in post_form %}
            <div class="form-floating mb-3 mt-3">
                {{ field }}
                {{ field.label_tag }}
            </div>
        {% endfor %}
        {{post_form.media}}
        <button class="btn btn-primary" type="submit">Wyślij</button>
    </div>
{% endblock %}